framework-config: 1.0
to_beans:
  - name: #instance名
    type: #classFileの場所
  - name: #instance名
    type: #classFileの場所
global-forwards: #アプリケーション共通のフォワード定義
 - name: link
   path: test_link.jsp
   redirect: #redirectするかforwardするかをtrueかfalseで指定。（trueがredirect）
   #contextRelative:
   #module:
   #className:
action-mappings:
 - name: #このアクションで使用するToオブジェクト
   type: #呼び出すアクションを実装しているアクションクラス
   path: #呼び出すアクション
   input: #このアクションの入力ページ(jsp)
   scope: request #requestかsessionを指定可能。sessionが指定されていた場合は、
   forward: #アクションごとのフォワード定義
    - name: success #遷移先の論理名
      path: /hogehoge.jsp #遷移先の実際のパス名
    - name: error
      path: /errorhoge.jsp
    - name: test
      path: /test.jsp
   #attribute:
   #className:
   #forward:
   #id:
   #include:
   #parameter:
   #prefix:
   #unknown:
   #validate:
